// ── Blog Themes Configuration ──────────────────────────────────
// 25 profession-specific templates for Kotha.blog
// Each theme is a complete visual identity for tenant blog sites.

import type { BlogTheme } from "@/lib/db";

export type ThemeConfig = {
  id: BlogTheme;
  name: string;
  profession: string;
  description: string;
  // Colors
  bg: string;
  bgSecondary: string;
  text: string;
  textSecondary: string;
  accent: string;
  accentHover: string;
  border: string;
  cardBg: string;
  // Typography
  headingFont: string;
  bodyFont: string;
  // Header
  headerBg: string;
  headerText: string;
  headerAccent: string;
  // Post card
  postHoverBg: string;
  tagBg: string;
  tagText: string;
  // Code blocks
  codeBg: string;
  codeText: string;
  // Blockquote
  quoteBorder: string;
  quoteText: string;
  // Footer
  footerBg: string;
  footerText: string;
  // Special
  gradientFrom?: string;
  gradientTo?: string;
  avatarGradient: string;
  navStyle: "transparent" | "solid" | "glass";
  bodyClass: string;
  // Preview
  previewColor: string;
};

export const THEMES: Record<BlogTheme, ThemeConfig> = {
  // ── 1. Minimal (General Blogging) ──────────────────────────
  minimal: {
    id: "minimal",
    name: "Minimal",
    profession: "General",
    description: "Clean Swiss design with generous whitespace",
    bg: "#fafaf9",
    bgSecondary: "#ffffff",
    text: "#1c1917",
    textSecondary: "#78716c",
    accent: "#0d9488",
    accentHover: "#0f766e",
    border: "#e7e5e4",
    cardBg: "#ffffff",
    headingFont: "'Lora', var(--font-lora), Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#fafaf9",
    headerText: "#1c1917",
    headerAccent: "#0d9488",
    postHoverBg: "#f5f5f4",
    tagBg: "#f0fdfa",
    tagText: "#0d9488",
    codeBg: "#1c1917",
    codeText: "#e7e5e4",
    quoteBorder: "#0d9488",
    quoteText: "#57534e",
    footerBg: "#fafaf9",
    footerText: "#a8a29e",
    avatarGradient: "linear-gradient(135deg, #0d9488, #059669)",
    navStyle: "transparent",
    bodyClass: "",
    previewColor: "#fafaf9",
  },

  // ── 2. Dark Noir (Developers/Tech) ─────────────────────────
  "dark-noir": {
    id: "dark-noir",
    name: "Dark Noir",
    profession: "Developers & Tech",
    description: "Dramatic dark background with bold typography",
    bg: "#0a0a0a",
    bgSecondary: "#141414",
    text: "#e5e5e5",
    textSecondary: "#737373",
    accent: "#f5f5f5",
    accentHover: "#d4d4d4",
    border: "#262626",
    cardBg: "#141414",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#0a0a0a",
    headerText: "#f5f5f5",
    headerAccent: "#ffffff",
    postHoverBg: "#1a1a1a",
    tagBg: "rgba(255,255,255,0.06)",
    tagText: "#a3a3a3",
    codeBg: "#1a1a1a",
    codeText: "#a3e635",
    quoteBorder: "#404040",
    quoteText: "#a3a3a3",
    footerBg: "#0a0a0a",
    footerText: "#525252",
    avatarGradient: "linear-gradient(135deg, #404040, #262626)",
    navStyle: "solid",
    bodyClass: "dark-noir-theme",
    previewColor: "#0f0f0f",
  },

  // ── 3. Vintage Press (Journalists/Writers) ─────────────────
  "vintage-press": {
    id: "vintage-press",
    name: "Vintage Press",
    profession: "Journalists & Writers",
    description: "Editorial newspaper aesthetic with serif elegance",
    bg: "#f5f0e8",
    bgSecondary: "#faf7f2",
    text: "#2c2416",
    textSecondary: "#8b7e6a",
    accent: "#8b4513",
    accentHover: "#6d3710",
    border: "#d4c9b8",
    cardBg: "#faf7f2",
    headingFont: "'Playfair Display', 'Lora', var(--font-lora), Georgia, serif",
    bodyFont: "'Lora', var(--font-lora), Georgia, serif",
    headerBg: "#f5f0e8",
    headerText: "#2c2416",
    headerAccent: "#8b4513",
    postHoverBg: "#efe8db",
    tagBg: "#e8dcc8",
    tagText: "#6d5b3e",
    codeBg: "#2c2416",
    codeText: "#d4c9b8",
    quoteBorder: "#8b4513",
    quoteText: "#6d5b3e",
    footerBg: "#efe8db",
    footerText: "#a89a82",
    avatarGradient: "linear-gradient(135deg, #8b4513, #a0522d)",
    navStyle: "transparent",
    bodyClass: "vintage-press-theme",
    previewColor: "#f5f0e8",
  },

  // ── 4. Neon Vapor (Gamers/Streamers) ────────────────────────
  "neon-vapor": {
    id: "neon-vapor",
    name: "Neon Vapor",
    profession: "Gamers & Streamers",
    description: "Cyberpunk neon glows and futuristic gradients",
    bg: "#0d0221",
    bgSecondary: "#150535",
    text: "#e0d7ff",
    textSecondary: "#8b7ec8",
    accent: "#ff2d95",
    accentHover: "#e0196e",
    border: "#2a1650",
    cardBg: "#150535",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#0d0221",
    headerText: "#e0d7ff",
    headerAccent: "#ff2d95",
    postHoverBg: "#1a0a3a",
    tagBg: "rgba(255,45,149,0.12)",
    tagText: "#ff2d95",
    codeBg: "#0a0118",
    codeText: "#00ff88",
    quoteBorder: "#ff2d95",
    quoteText: "#8b7ec8",
    footerBg: "#0d0221",
    footerText: "#4a3b6b",
    gradientFrom: "#ff2d95",
    gradientTo: "#00d4ff",
    avatarGradient: "linear-gradient(135deg, #ff2d95, #00d4ff)",
    navStyle: "glass",
    bodyClass: "neon-vapor-theme",
    previewColor: "#1a0a2e",
  },

  // ── 5. Forest (Nature/Environment) ──────────────────────────
  forest: {
    id: "forest",
    name: "Forest",
    profession: "Nature & Environment",
    description: "Earthy natural tones with organic warmth",
    bg: "#f0f4ed",
    bgSecondary: "#f8faf6",
    text: "#1a2e1a",
    textSecondary: "#4a6741",
    accent: "#2d6a4f",
    accentHover: "#1b4332",
    border: "#c8d5c1",
    cardBg: "#f8faf6",
    headingFont: "'Lora', var(--font-lora), Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#f0f4ed",
    headerText: "#1a2e1a",
    headerAccent: "#2d6a4f",
    postHoverBg: "#e4ece0",
    tagBg: "#d8e8d0",
    tagText: "#2d6a4f",
    codeBg: "#1a2e1a",
    codeText: "#a7c9a0",
    quoteBorder: "#2d6a4f",
    quoteText: "#4a6741",
    footerBg: "#e8ede5",
    footerText: "#7a9171",
    avatarGradient: "linear-gradient(135deg, #2d6a4f, #52b788)",
    navStyle: "transparent",
    bodyClass: "forest-theme",
    previewColor: "#f0f4ed",
  },

  // ── 6. Ocean Breeze (Travel/Adventure) ──────────────────────
  "ocean-breeze": {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    profession: "Travel & Adventure",
    description: "Calm blue tones, professional and serene",
    bg: "#f0f7ff",
    bgSecondary: "#ffffff",
    text: "#0c2d48",
    textSecondary: "#5b8db8",
    accent: "#0077b6",
    accentHover: "#005f8d",
    border: "#c9dff0",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "linear-gradient(135deg, #0077b6, #00a8e8)",
    headerText: "#ffffff",
    headerAccent: "#90e0ef",
    postHoverBg: "#e5f0fa",
    tagBg: "#dbeafe",
    tagText: "#0077b6",
    codeBg: "#0c2d48",
    codeText: "#90e0ef",
    quoteBorder: "#0077b6",
    quoteText: "#5b8db8",
    footerBg: "#e5f0fa",
    footerText: "#7baac7",
    gradientFrom: "#0077b6",
    gradientTo: "#00a8e8",
    avatarGradient: "linear-gradient(135deg, #0077b6, #00a8e8)",
    navStyle: "solid",
    bodyClass: "ocean-breeze-theme",
    previewColor: "#f0f7ff",
  },

  // ── 7. Poet's Quill (Poets & Lyricists) ─────────────────────
  "poets-quill": {
    id: "poets-quill",
    name: "Poet's Quill",
    profession: "Poets & Lyricists",
    description: "Elegant parchment tones with flowing serif typography",
    bg: "#fdf8f0",
    bgSecondary: "#fffcf5",
    text: "#3d2b1f",
    textSecondary: "#8a6d4b",
    accent: "#b8860b",
    accentHover: "#996f0a",
    border: "#e8d5b7",
    cardBg: "#fffcf5",
    headingFont: "'Lora', var(--font-lora), 'Palatino Linotype', Georgia, serif",
    bodyFont: "'Lora', var(--font-lora), Georgia, serif",
    headerBg: "#fdf8f0",
    headerText: "#3d2b1f",
    headerAccent: "#b8860b",
    postHoverBg: "#f5ead6",
    tagBg: "#f0e0c0",
    tagText: "#8a6d4b",
    codeBg: "#3d2b1f",
    codeText: "#e8d5b7",
    quoteBorder: "#b8860b",
    quoteText: "#8a6d4b",
    footerBg: "#f5ead6",
    footerText: "#b09979",
    avatarGradient: "linear-gradient(135deg, #b8860b, #daa520)",
    navStyle: "transparent",
    bodyClass: "poets-quill-theme",
    previewColor: "#fdf8f0",
  },

  // ── 8. Code Terminal (Software Engineers) ────────────────────
  "code-terminal": {
    id: "code-terminal",
    name: "Code Terminal",
    profession: "Software Engineers",
    description: "Hacker-style terminal with monospace and green accents",
    bg: "#0c0c0c",
    bgSecondary: "#161616",
    text: "#d4d4d4",
    textSecondary: "#6a9955",
    accent: "#4ec9b0",
    accentHover: "#3ba18c",
    border: "#2d2d2d",
    cardBg: "#1e1e1e",
    headingFont: "var(--font-geist-mono), 'Fira Code', 'Cascadia Mono', monospace",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#0c0c0c",
    headerText: "#4ec9b0",
    headerAccent: "#4ec9b0",
    postHoverBg: "#1e1e1e",
    tagBg: "rgba(78,201,176,0.1)",
    tagText: "#4ec9b0",
    codeBg: "#1e1e1e",
    codeText: "#d7ba7d",
    quoteBorder: "#4ec9b0",
    quoteText: "#6a9955",
    footerBg: "#0c0c0c",
    footerText: "#4b4b4b",
    gradientFrom: "#4ec9b0",
    gradientTo: "#569cd6",
    avatarGradient: "linear-gradient(135deg, #4ec9b0, #569cd6)",
    navStyle: "solid",
    bodyClass: "code-terminal-theme",
    previewColor: "#0c0c0c",
  },

  // ── 9. Medical Journal (Doctors & Health) ────────────────────
  "medical-journal": {
    id: "medical-journal",
    name: "Medical Journal",
    profession: "Doctors & Healthcare",
    description: "Clean clinical design with trust-building blue tones",
    bg: "#f8fbff",
    bgSecondary: "#ffffff",
    text: "#1a2332",
    textSecondary: "#5a7a9a",
    accent: "#2563eb",
    accentHover: "#1d4ed8",
    border: "#dce8f5",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#f8fbff",
    headerText: "#1a2332",
    headerAccent: "#2563eb",
    postHoverBg: "#eef4fc",
    tagBg: "#dbeafe",
    tagText: "#2563eb",
    codeBg: "#1e293b",
    codeText: "#93c5fd",
    quoteBorder: "#2563eb",
    quoteText: "#5a7a9a",
    footerBg: "#f0f5fc",
    footerText: "#8ea7c4",
    avatarGradient: "linear-gradient(135deg, #2563eb, #3b82f6)",
    navStyle: "solid",
    bodyClass: "medical-journal-theme",
    previewColor: "#f8fbff",
  },

  // ── 10. Blueprint (Engineers & Architects) ───────────────────
  blueprint: {
    id: "blueprint",
    name: "Blueprint",
    profession: "Engineers & Architects",
    description: "Technical grid design with drafting-table aesthetics",
    bg: "#f0f4f8",
    bgSecondary: "#ffffff",
    text: "#1e3a5f",
    textSecondary: "#5b7fa3",
    accent: "#0f4c81",
    accentHover: "#0a3560",
    border: "#c5d5e5",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#0f4c81",
    headerText: "#ffffff",
    headerAccent: "#87ceeb",
    postHoverBg: "#e4ecf5",
    tagBg: "#d0e0f0",
    tagText: "#0f4c81",
    codeBg: "#1e3a5f",
    codeText: "#87ceeb",
    quoteBorder: "#0f4c81",
    quoteText: "#5b7fa3",
    footerBg: "#e4ecf5",
    footerText: "#8aa5c0",
    avatarGradient: "linear-gradient(135deg, #0f4c81, #1a6fb5)",
    navStyle: "solid",
    bodyClass: "blueprint-theme",
    previewColor: "#f0f4f8",
  },

  // ── 11. Gallery Canvas (Artists & Designers) ─────────────────
  "gallery-canvas": {
    id: "gallery-canvas",
    name: "Gallery Canvas",
    profession: "Artists & Designers",
    description: "Gallery-style layout with large media focus",
    bg: "#f5f5f5",
    bgSecondary: "#ffffff",
    text: "#1a1a1a",
    textSecondary: "#6b6b6b",
    accent: "#e63946",
    accentHover: "#c1121f",
    border: "#e0e0e0",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#1a1a1a",
    headerText: "#ffffff",
    headerAccent: "#e63946",
    postHoverBg: "#ebebeb",
    tagBg: "#fce4ec",
    tagText: "#e63946",
    codeBg: "#263238",
    codeText: "#80cbc4",
    quoteBorder: "#e63946",
    quoteText: "#6b6b6b",
    footerBg: "#1a1a1a",
    footerText: "#888888",
    avatarGradient: "linear-gradient(135deg, #e63946, #f4a261)",
    navStyle: "solid",
    bodyClass: "gallery-canvas-theme",
    previewColor: "#f5f5f5",
  },

  // ── 12. Sunset Warmth (Content Creators) ─────────────────────
  "sunset-warmth": {
    id: "sunset-warmth",
    name: "Sunset Warmth",
    profession: "Content Creators",
    description: "Warm golden tones with an inviting creator vibe",
    bg: "#fffbf5",
    bgSecondary: "#ffffff",
    text: "#2d1b00",
    textSecondary: "#8b6914",
    accent: "#e67e22",
    accentHover: "#d35400",
    border: "#f0dfc0",
    cardBg: "#ffffff",
    headingFont: "'Lora', var(--font-lora), Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "linear-gradient(135deg, #e67e22, #f39c12)",
    headerText: "#ffffff",
    headerAccent: "#ffe8c0",
    postHoverBg: "#fff3e0",
    tagBg: "#fff3e0",
    tagText: "#e67e22",
    codeBg: "#2d1b00",
    codeText: "#f0c674",
    quoteBorder: "#e67e22",
    quoteText: "#8b6914",
    footerBg: "#fff3e0",
    footerText: "#c49a46",
    gradientFrom: "#e67e22",
    gradientTo: "#f39c12",
    avatarGradient: "linear-gradient(135deg, #e67e22, #f39c12)",
    navStyle: "solid",
    bodyClass: "sunset-warmth-theme",
    previewColor: "#fffbf5",
  },

  // ── 13. Newsroom (News & Current Affairs) ───────────────────
  newsroom: {
    id: "newsroom",
    name: "Newsroom",
    profession: "News & Media",
    description: "Bold newspaper layout with strong headlines",
    bg: "#fafafa",
    bgSecondary: "#ffffff",
    text: "#111111",
    textSecondary: "#555555",
    accent: "#c0392b",
    accentHover: "#a93226",
    border: "#d5d5d5",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Lora', var(--font-lora), Georgia, serif",
    headerBg: "#111111",
    headerText: "#ffffff",
    headerAccent: "#c0392b",
    postHoverBg: "#f0f0f0",
    tagBg: "#f8e8e6",
    tagText: "#c0392b",
    codeBg: "#1a1a1a",
    codeText: "#e6e6e6",
    quoteBorder: "#c0392b",
    quoteText: "#555555",
    footerBg: "#111111",
    footerText: "#777777",
    avatarGradient: "linear-gradient(135deg, #c0392b, #e74c3c)",
    navStyle: "solid",
    bodyClass: "newsroom-theme",
    previewColor: "#fafafa",
  },

  // ── 14. Zen Garden (Mindfulness & Wellness) ─────────────────
  "zen-garden": {
    id: "zen-garden",
    name: "Zen Garden",
    profession: "Mindfulness & Yoga",
    description: "Minimalist Japanese-inspired tranquility",
    bg: "#f7f5f0",
    bgSecondary: "#fdfcf8",
    text: "#2c2c2c",
    textSecondary: "#7a7a6e",
    accent: "#6b705c",
    accentHover: "#565b4c",
    border: "#ddd8cc",
    cardBg: "#fdfcf8",
    headingFont: "'Lora', var(--font-lora), 'Noto Serif', Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#f7f5f0",
    headerText: "#2c2c2c",
    headerAccent: "#6b705c",
    postHoverBg: "#edeae0",
    tagBg: "#e8e4d8",
    tagText: "#6b705c",
    codeBg: "#2c2c2c",
    codeText: "#b7b7a4",
    quoteBorder: "#a5a58d",
    quoteText: "#7a7a6e",
    footerBg: "#edeae0",
    footerText: "#a0997a",
    avatarGradient: "linear-gradient(135deg, #6b705c, #a5a58d)",
    navStyle: "transparent",
    bodyClass: "zen-garden-theme",
    previewColor: "#f7f5f0",
  },

  // ── 15. Startup Pitch (Entrepreneurs) ───────────────────────
  "startup-pitch": {
    id: "startup-pitch",
    name: "Startup Pitch",
    profession: "Entrepreneurs & Startups",
    description: "Modern SaaS-style with gradient accents",
    bg: "#fafbff",
    bgSecondary: "#ffffff",
    text: "#0f172a",
    textSecondary: "#64748b",
    accent: "#7c3aed",
    accentHover: "#6d28d9",
    border: "#e2e8f0",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "linear-gradient(135deg, #7c3aed, #a855f7)",
    headerText: "#ffffff",
    headerAccent: "#ddd6fe",
    postHoverBg: "#f1f0ff",
    tagBg: "#ede9fe",
    tagText: "#7c3aed",
    codeBg: "#1e1b4b",
    codeText: "#c4b5fd",
    quoteBorder: "#7c3aed",
    quoteText: "#64748b",
    footerBg: "#f5f3ff",
    footerText: "#a5b4fc",
    gradientFrom: "#7c3aed",
    gradientTo: "#a855f7",
    avatarGradient: "linear-gradient(135deg, #7c3aed, #a855f7)",
    navStyle: "solid",
    bodyClass: "startup-pitch-theme",
    previewColor: "#fafbff",
  },

  // ── 16. Academic Paper (Researchers/Professors) ──────────────
  "academic-paper": {
    id: "academic-paper",
    name: "Academic Paper",
    profession: "Researchers & Professors",
    description: "Scholarly design for research and academic writing",
    bg: "#fafafa",
    bgSecondary: "#ffffff",
    text: "#1a1a2e",
    textSecondary: "#6b6b80",
    accent: "#16213e",
    accentHover: "#0f3460",
    border: "#d8d8e0",
    cardBg: "#ffffff",
    headingFont: "'Lora', var(--font-lora), 'Times New Roman', Georgia, serif",
    bodyFont: "'Lora', var(--font-lora), Georgia, serif",
    headerBg: "#1a1a2e",
    headerText: "#ffffff",
    headerAccent: "#e9ecef",
    postHoverBg: "#f0f0f5",
    tagBg: "#e8e8f0",
    tagText: "#1a1a2e",
    codeBg: "#1a1a2e",
    codeText: "#a8b2d1",
    quoteBorder: "#16213e",
    quoteText: "#6b6b80",
    footerBg: "#f0f0f5",
    footerText: "#9090a0",
    avatarGradient: "linear-gradient(135deg, #16213e, #0f3460)",
    navStyle: "solid",
    bodyClass: "academic-paper-theme",
    previewColor: "#fafafa",
  },

  // ── 17. Fashion Editorial (Fashion & Beauty) ────────────────
  "fashion-editorial": {
    id: "fashion-editorial",
    name: "Fashion Editorial",
    profession: "Fashion & Beauty",
    description: "High-contrast magazine with elegant typography",
    bg: "#ffffff",
    bgSecondary: "#fafafa",
    text: "#111111",
    textSecondary: "#666666",
    accent: "#c9184a",
    accentHover: "#a4133c",
    border: "#e8e8e8",
    cardBg: "#fafafa",
    headingFont: "'Lora', var(--font-lora), 'Didot', Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#ffffff",
    headerText: "#111111",
    headerAccent: "#c9184a",
    postHoverBg: "#f5f5f5",
    tagBg: "#fce4ec",
    tagText: "#c9184a",
    codeBg: "#111111",
    codeText: "#f8bbd0",
    quoteBorder: "#c9184a",
    quoteText: "#666666",
    footerBg: "#fafafa",
    footerText: "#999999",
    avatarGradient: "linear-gradient(135deg, #c9184a, #ff6d00)",
    navStyle: "transparent",
    bodyClass: "fashion-editorial-theme",
    previewColor: "#ffffff",
  },

  // ── 18. Music Studio (Musicians) ────────────────────────────
  "music-studio": {
    id: "music-studio",
    name: "Music Studio",
    profession: "Musicians & Producers",
    description: "Dark atmosphere with vibrant neon audio accents",
    bg: "#121212",
    bgSecondary: "#1a1a1a",
    text: "#e0e0e0",
    textSecondary: "#888888",
    accent: "#1db954",
    accentHover: "#1aa34a",
    border: "#2a2a2a",
    cardBg: "#1e1e1e",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#121212",
    headerText: "#ffffff",
    headerAccent: "#1db954",
    postHoverBg: "#222222",
    tagBg: "rgba(29,185,84,0.12)",
    tagText: "#1db954",
    codeBg: "#0a0a0a",
    codeText: "#1db954",
    quoteBorder: "#1db954",
    quoteText: "#888888",
    footerBg: "#0a0a0a",
    footerText: "#555555",
    gradientFrom: "#1db954",
    gradientTo: "#191414",
    avatarGradient: "linear-gradient(135deg, #1db954, #1ed760)",
    navStyle: "solid",
    bodyClass: "music-studio-theme",
    previewColor: "#121212",
  },

  // ── 19. Food & Recipe (Food Bloggers/Chefs) ──────────────────
  "food-recipe": {
    id: "food-recipe",
    name: "Food & Recipe",
    profession: "Food Bloggers & Chefs",
    description: "Warm inviting tones perfect for culinary content",
    bg: "#fef9f4",
    bgSecondary: "#ffffff",
    text: "#3c1e08",
    textSecondary: "#8b6141",
    accent: "#d4521e",
    accentHover: "#b5441a",
    border: "#f0dcc8",
    cardBg: "#ffffff",
    headingFont: "'Lora', var(--font-lora), Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#fef9f4",
    headerText: "#3c1e08",
    headerAccent: "#d4521e",
    postHoverBg: "#fdf0e0",
    tagBg: "#fde8d0",
    tagText: "#d4521e",
    codeBg: "#3c1e08",
    codeText: "#f0c694",
    quoteBorder: "#d4521e",
    quoteText: "#8b6141",
    footerBg: "#fdf0e0",
    footerText: "#c49060",
    avatarGradient: "linear-gradient(135deg, #d4521e, #f0a050)",
    navStyle: "transparent",
    bodyClass: "food-recipe-theme",
    previewColor: "#fef9f4",
  },

  // ── 20. Legal Brief (Lawyers & Legal) ───────────────────────
  "legal-brief": {
    id: "legal-brief",
    name: "Legal Brief",
    profession: "Lawyers & Legal",
    description: "Professional structured design for legal content",
    bg: "#f8f8fa",
    bgSecondary: "#ffffff",
    text: "#1a1a2e",
    textSecondary: "#6e6e82",
    accent: "#2c3e50",
    accentHover: "#1a252f",
    border: "#d0d0da",
    cardBg: "#ffffff",
    headingFont: "'Lora', var(--font-lora), 'Garamond', Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#2c3e50",
    headerText: "#ecf0f1",
    headerAccent: "#bdc3c7",
    postHoverBg: "#eeeff2",
    tagBg: "#e0e2e8",
    tagText: "#2c3e50",
    codeBg: "#2c3e50",
    codeText: "#bdc3c7",
    quoteBorder: "#2c3e50",
    quoteText: "#6e6e82",
    footerBg: "#ecedee",
    footerText: "#95959f",
    avatarGradient: "linear-gradient(135deg, #2c3e50, #34495e)",
    navStyle: "solid",
    bodyClass: "legal-brief-theme",
    previewColor: "#f8f8fa",
  },

  // ── 21. Photography (Photographers) ─────────────────────────
  photography: {
    id: "photography",
    name: "Photography",
    profession: "Photographers",
    description: "Dark background with image-first cinematic layout",
    bg: "#0f0f0f",
    bgSecondary: "#1a1a1a",
    text: "#f0f0f0",
    textSecondary: "#999999",
    accent: "#f0c14b",
    accentHover: "#d4a83a",
    border: "#333333",
    cardBg: "#1a1a1a",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#0f0f0f",
    headerText: "#f0f0f0",
    headerAccent: "#f0c14b",
    postHoverBg: "#222222",
    tagBg: "rgba(240,193,75,0.1)",
    tagText: "#f0c14b",
    codeBg: "#1a1a1a",
    codeText: "#f0c14b",
    quoteBorder: "#f0c14b",
    quoteText: "#999999",
    footerBg: "#0a0a0a",
    footerText: "#555555",
    avatarGradient: "linear-gradient(135deg, #f0c14b, #e0a020)",
    navStyle: "glass",
    bodyClass: "photography-theme",
    previewColor: "#0f0f0f",
  },

  // ── 22. Wellness (Health & Wellness) ────────────────────────
  wellness: {
    id: "wellness",
    name: "Wellness",
    profession: "Health & Wellness",
    description: "Soft pastels with calming, nurturing aesthetics",
    bg: "#faf5f0",
    bgSecondary: "#ffffff",
    text: "#2d2d2d",
    textSecondary: "#8a7a6e",
    accent: "#e8998d",
    accentHover: "#d47a6d",
    border: "#ede0d4",
    cardBg: "#ffffff",
    headingFont: "'Lora', var(--font-lora), Georgia, serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#faf5f0",
    headerText: "#2d2d2d",
    headerAccent: "#e8998d",
    postHoverBg: "#f5ece5",
    tagBg: "#fce8e4",
    tagText: "#d47a6d",
    codeBg: "#2d2d2d",
    codeText: "#e8998d",
    quoteBorder: "#e8998d",
    quoteText: "#8a7a6e",
    footerBg: "#f0e8e0",
    footerText: "#baa892",
    avatarGradient: "linear-gradient(135deg, #e8998d, #f2c4b8)",
    navStyle: "transparent",
    bodyClass: "wellness-theme",
    previewColor: "#faf5f0",
  },

  // ── 23. Sports Arena (Sports & Fitness) ─────────────────────
  "sports-arena": {
    id: "sports-arena",
    name: "Sports Arena",
    profession: "Sports & Fitness",
    description: "Bold energetic design with dynamic colors",
    bg: "#f4f4f4",
    bgSecondary: "#ffffff",
    text: "#1a1a2e",
    textSecondary: "#6c6c80",
    accent: "#e63946",
    accentHover: "#c0392b",
    border: "#d8d8e0",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "linear-gradient(135deg, #1a1a2e, #16213e)",
    headerText: "#ffffff",
    headerAccent: "#e63946",
    postHoverBg: "#ebebf0",
    tagBg: "#fce4e6",
    tagText: "#e63946",
    codeBg: "#1a1a2e",
    codeText: "#e8e8f0",
    quoteBorder: "#e63946",
    quoteText: "#6c6c80",
    footerBg: "#1a1a2e",
    footerText: "#8080a0",
    gradientFrom: "#e63946",
    gradientTo: "#1a1a2e",
    avatarGradient: "linear-gradient(135deg, #e63946, #ff6b6b)",
    navStyle: "solid",
    bodyClass: "sports-arena-theme",
    previewColor: "#f4f4f4",
  },

  // ── 24. Kids & Education (Teachers/Educators) ───────────────
  "kids-education": {
    id: "kids-education",
    name: "Kids & Education",
    profession: "Teachers & Educators",
    description: "Colorful playful design for educational content",
    bg: "#fffdf7",
    bgSecondary: "#ffffff",
    text: "#1a1a2e",
    textSecondary: "#6b6b80",
    accent: "#6366f1",
    accentHover: "#4f46e5",
    border: "#e0e0f0",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "linear-gradient(135deg, #6366f1, #8b5cf6, #a855f7)",
    headerText: "#ffffff",
    headerAccent: "#e0e7ff",
    postHoverBg: "#f5f3ff",
    tagBg: "#e0e7ff",
    tagText: "#6366f1",
    codeBg: "#312e81",
    codeText: "#c7d2fe",
    quoteBorder: "#6366f1",
    quoteText: "#6b6b80",
    footerBg: "#f5f3ff",
    footerText: "#a5b4fc",
    gradientFrom: "#6366f1",
    gradientTo: "#a855f7",
    avatarGradient: "linear-gradient(135deg, #6366f1, #f59e0b)",
    navStyle: "solid",
    bodyClass: "kids-education-theme",
    previewColor: "#fffdf7",
  },

  // ── 25. Corporate Pro (Business Professionals) ──────────────
  "corporate-pro": {
    id: "corporate-pro",
    name: "Corporate Pro",
    profession: "Business & Corporate",
    description: "Executive polished design for business leaders",
    bg: "#fafbfc",
    bgSecondary: "#ffffff",
    text: "#0d1b2a",
    textSecondary: "#415a77",
    accent: "#1b4965",
    accentHover: "#143a52",
    border: "#d4dce5",
    cardBg: "#ffffff",
    headingFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    bodyFont: "'Inter', var(--font-geist-sans), system-ui, sans-serif",
    headerBg: "#0d1b2a",
    headerText: "#ffffff",
    headerAccent: "#5fa8d3",
    postHoverBg: "#eef2f6",
    tagBg: "#e0ecf4",
    tagText: "#1b4965",
    codeBg: "#0d1b2a",
    codeText: "#5fa8d3",
    quoteBorder: "#1b4965",
    quoteText: "#415a77",
    footerBg: "#0d1b2a",
    footerText: "#5fa8d3",
    avatarGradient: "linear-gradient(135deg, #1b4965, #5fa8d3)",
    navStyle: "solid",
    bodyClass: "corporate-pro-theme",
    previewColor: "#fafbfc",
  },
};

export function getTheme(id: BlogTheme): ThemeConfig {
  return THEMES[id] || THEMES.minimal;
}
